//
// WARNING! All changes made in this file will be lost!
// Created from 'scheme.tl' by 'mtprotoc'
//
// Copyright (c) 2024-present,  Teamgram Authors.
//  All rights reserved.
//
// Author: teamgramio (teamgram.io@gmail.com)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: help.tl.proto

package help

import (
	_ "github.com/teamgram/proto/mtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TLConstructor int32

const (
	TLConstructor_CRC32_UNKNOWN               TLConstructor = 0
	TLConstructor_CRC32_help_getCountriesList TLConstructor = 1935116200
)

// Enum value maps for TLConstructor.
var (
	TLConstructor_name = map[int32]string{
		0:          "CRC32_UNKNOWN",
		1935116200: "CRC32_help_getCountriesList",
	}
	TLConstructor_value = map[string]int32{
		"CRC32_UNKNOWN":               0,
		"CRC32_help_getCountriesList": 1935116200,
	}
)

func (x TLConstructor) Enum() *TLConstructor {
	p := new(TLConstructor)
	*p = x
	return p
}

func (x TLConstructor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TLConstructor) Descriptor() protoreflect.EnumDescriptor {
	return file_help_tl_proto_enumTypes[0].Descriptor()
}

func (TLConstructor) Type() protoreflect.EnumType {
	return &file_help_tl_proto_enumTypes[0]
}

func (x TLConstructor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TLConstructor.Descriptor instead.
func (TLConstructor) EnumDescriptor() ([]byte, []int) {
	return file_help_tl_proto_rawDescGZIP(), []int{0}
}

// HelpGetCountriesList
// help.getCountriesList = help.CountriesList;
type TLHelpGetCountriesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constructor   TLConstructor          `protobuf:"varint,1,opt,name=constructor,proto3,enum=help.TLConstructor" json:"constructor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLHelpGetCountriesList) Reset() {
	*x = TLHelpGetCountriesList{}
	mi := &file_help_tl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLHelpGetCountriesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLHelpGetCountriesList) ProtoMessage() {}

func (x *TLHelpGetCountriesList) ProtoReflect() protoreflect.Message {
	mi := &file_help_tl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLHelpGetCountriesList.ProtoReflect.Descriptor instead.
func (*TLHelpGetCountriesList) Descriptor() ([]byte, []int) {
	return file_help_tl_proto_rawDescGZIP(), []int{0}
}

func (x *TLHelpGetCountriesList) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

// Help_CountriesList
type Help_CountriesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*Help_Country        `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	Hash          int32                  `protobuf:"varint,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Help_CountriesList) Reset() {
	*x = Help_CountriesList{}
	mi := &file_help_tl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Help_CountriesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Help_CountriesList) ProtoMessage() {}

func (x *Help_CountriesList) ProtoReflect() protoreflect.Message {
	mi := &file_help_tl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Help_CountriesList.ProtoReflect.Descriptor instead.
func (*Help_CountriesList) Descriptor() ([]byte, []int) {
	return file_help_tl_proto_rawDescGZIP(), []int{1}
}

func (x *Help_CountriesList) GetCountries() []*Help_Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *Help_CountriesList) GetHash() int32 {
	if x != nil {
		return x.Hash
	}
	return 0
}

// Help_Country
type Help_Country struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Hidden        bool                    `protobuf:"varint,1,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Iso2          string                  `protobuf:"bytes,2,opt,name=iso2,proto3" json:"iso2,omitempty"`
	DefaultName   string                  `protobuf:"bytes,3,opt,name=default_name,json=defaultName,proto3" json:"default_name,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CountryCodes  []*Help_CountryCode     `protobuf:"bytes,5,rep,name=country_codes,json=countryCodes,proto3" json:"country_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Help_Country) Reset() {
	*x = Help_Country{}
	mi := &file_help_tl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Help_Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Help_Country) ProtoMessage() {}

func (x *Help_Country) ProtoReflect() protoreflect.Message {
	mi := &file_help_tl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Help_Country.ProtoReflect.Descriptor instead.
func (*Help_Country) Descriptor() ([]byte, []int) {
	return file_help_tl_proto_rawDescGZIP(), []int{2}
}

func (x *Help_Country) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Help_Country) GetIso2() string {
	if x != nil {
		return x.Iso2
	}
	return ""
}

func (x *Help_Country) GetDefaultName() string {
	if x != nil {
		return x.DefaultName
	}
	return ""
}

func (x *Help_Country) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Help_Country) GetCountryCodes() []*Help_CountryCode {
	if x != nil {
		return x.CountryCodes
	}
	return nil
}

// Help_CountryCode
type Help_CountryCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Prefixes      []string               `protobuf:"bytes,2,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	Patterns      []string               `protobuf:"bytes,3,rep,name=patterns,proto3" json:"patterns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Help_CountryCode) Reset() {
	*x = Help_CountryCode{}
	mi := &file_help_tl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Help_CountryCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Help_CountryCode) ProtoMessage() {}

func (x *Help_CountryCode) ProtoReflect() protoreflect.Message {
	mi := &file_help_tl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Help_CountryCode.ProtoReflect.Descriptor instead.
func (*Help_CountryCode) Descriptor() ([]byte, []int) {
	return file_help_tl_proto_rawDescGZIP(), []int{3}
}

func (x *Help_CountryCode) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Help_CountryCode) GetPrefixes() []string {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *Help_CountryCode) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

var File_help_tl_proto protoreflect.FileDescriptor

const file_help_tl_proto_rawDesc = "" +
	"\n" +
	"\rhelp.tl.proto\x12\x04help\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1aschema.tl.core_types.proto\x1a\x19schema.tl.transport.proto\x1a\x14schema.tl.sync.proto\"Q\n" +
	"\x18TL_help_getCountriesList\x125\n" +
	"\vconstructor\x18\x01 \x01(\x0e2\x13.help.TLConstructorR\vconstructor\"Z\n" +
	"\x12Help_CountriesList\x120\n" +
	"\tcountries\x18\x01 \x03(\v2\x12.help.Help_CountryR\tcountries\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\x05R\x04hash\"\xcc\x01\n" +
	"\fHelp_Country\x12\x16\n" +
	"\x06hidden\x18\x01 \x01(\bR\x06hidden\x12\x12\n" +
	"\x04iso2\x18\x02 \x01(\tR\x04iso2\x12!\n" +
	"\fdefault_name\x18\x03 \x01(\tR\vdefaultName\x120\n" +
	"\x04name\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x12;\n" +
	"\rcountry_codes\x18\x05 \x03(\v2\x16.help.Help_CountryCodeR\fcountryCodes\"m\n" +
	"\x10Help_CountryCode\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12\x1a\n" +
	"\bprefixes\x18\x02 \x03(\tR\bprefixes\x12\x1a\n" +
	"\bpatterns\x18\x03 \x03(\tR\bpatterns*G\n" +
	"\rTLConstructor\x12\x11\n" +
	"\rCRC32_UNKNOWN\x10\x00\x12#\n" +
	"\x1bCRC32_help_getCountriesList\x10\xa8\x8fޚ\a2^\n" +
	"\aRPCHelp\x12S\n" +
	"\x15help_getCountriesList\x12\x1e.help.TL_help_getCountriesList\x1a\x18.help.Help_CountriesList\"\x00B?Z=github.com/teamgram/teamgram-server/app/service/biz/help/helpb\x06proto3"

var (
	file_help_tl_proto_rawDescOnce sync.Once
	file_help_tl_proto_rawDescData []byte
)

func file_help_tl_proto_rawDescGZIP() []byte {
	file_help_tl_proto_rawDescOnce.Do(func() {
		file_help_tl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_help_tl_proto_rawDesc), len(file_help_tl_proto_rawDesc)))
	})
	return file_help_tl_proto_rawDescData
}

var file_help_tl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_help_tl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_help_tl_proto_goTypes = []any{
	(TLConstructor)(0),             // 0: help.TLConstructor
	(*TLHelpGetCountriesList)(nil), // 1: help.TL_help_getCountriesList
	(*Help_CountriesList)(nil),     // 2: help.Help_CountriesList
	(*Help_Country)(nil),           // 3: help.Help_Country
	(*Help_CountryCode)(nil),       // 4: help.Help_CountryCode
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
}
var file_help_tl_proto_depIdxs = []int32{
	0, // 0: help.TL_help_getCountriesList.constructor:type_name -> help.TLConstructor
	3, // 1: help.Help_CountriesList.countries:type_name -> help.Help_Country
	5, // 2: help.Help_Country.name:type_name -> google.protobuf.StringValue
	4, // 3: help.Help_Country.country_codes:type_name -> help.Help_CountryCode
	1, // 4: help.RPCHelp.help_getCountriesList:input_type -> help.TL_help_getCountriesList
	2, // 5: help.RPCHelp.help_getCountriesList:output_type -> help.Help_CountriesList
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_help_tl_proto_init() }
func file_help_tl_proto_init() {
	if File_help_tl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_help_tl_proto_rawDesc), len(file_help_tl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_help_tl_proto_goTypes,
		DependencyIndexes: file_help_tl_proto_depIdxs,
		EnumInfos:         file_help_tl_proto_enumTypes,
		MessageInfos:      file_help_tl_proto_msgTypes,
	}.Build()
	File_help_tl_proto = out.File
	file_help_tl_proto_goTypes = nil
	file_help_tl_proto_depIdxs = nil
}
