//
// WARNING! All changes made in this file will be lost!
// Created from 'scheme.tl' by 'mtprotoc'
//
// Copyright (c) 2024-present,  Teamgram Authors.
//  All rights reserved.
//
// Author: teamgramio (teamgram.io@gmail.com)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: help.tl.proto

package help

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPCHelp_HelpGetCountriesList_FullMethodName = "/help.RPCHelp/help_getCountriesList"
)

// RPCHelpClient is the client API for RPCHelp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCHelpClient interface {
	HelpGetCountriesList(ctx context.Context, in *TLHelpGetCountriesList, opts ...grpc.CallOption) (*Help_CountriesList, error)
}

type rPCHelpClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCHelpClient(cc grpc.ClientConnInterface) RPCHelpClient {
	return &rPCHelpClient{cc}
}

func (c *rPCHelpClient) HelpGetCountriesList(ctx context.Context, in *TLHelpGetCountriesList, opts ...grpc.CallOption) (*Help_CountriesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Help_CountriesList)
	err := c.cc.Invoke(ctx, RPCHelp_HelpGetCountriesList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCHelpServer is the server API for RPCHelp service.
// All implementations should embed UnimplementedRPCHelpServer
// for forward compatibility.
type RPCHelpServer interface {
	HelpGetCountriesList(context.Context, *TLHelpGetCountriesList) (*Help_CountriesList, error)
}

// UnimplementedRPCHelpServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCHelpServer struct{}

func (UnimplementedRPCHelpServer) HelpGetCountriesList(context.Context, *TLHelpGetCountriesList) (*Help_CountriesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelpGetCountriesList not implemented")
}
func (UnimplementedRPCHelpServer) testEmbeddedByValue() {}

// UnsafeRPCHelpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCHelpServer will
// result in compilation errors.
type UnsafeRPCHelpServer interface {
	mustEmbedUnimplementedRPCHelpServer()
}

func RegisterRPCHelpServer(s grpc.ServiceRegistrar, srv RPCHelpServer) {
	// If the following call pancis, it indicates UnimplementedRPCHelpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPCHelp_ServiceDesc, srv)
}

func _RPCHelp_HelpGetCountriesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLHelpGetCountriesList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCHelpServer).HelpGetCountriesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCHelp_HelpGetCountriesList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCHelpServer).HelpGetCountriesList(ctx, req.(*TLHelpGetCountriesList))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCHelp_ServiceDesc is the grpc.ServiceDesc for RPCHelp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCHelp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "help.RPCHelp",
	HandlerType: (*RPCHelpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "help_getCountriesList",
			Handler:    _RPCHelp_HelpGetCountriesList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "help.tl.proto",
}
